# Translations template for manila.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the manila project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: manila 2015.1.dev79.g6c84cf0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-10-31 06:14+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: manila/context.py:59
#, python-format
msgid "Arguments dropped when creating context: %s"
msgstr ""

#: manila/context.py:96
#, python-format
msgid "read_deleted can only be one of 'no', 'yes' or 'only', not %r"
msgstr ""

#: manila/exception.py:68
msgid "An unknown exception occurred."
msgstr ""

#: manila/exception.py:92
msgid "Exception in string format operation."
msgstr ""

#: manila/exception.py:108
msgid "Exception due to network failure."
msgstr ""

#: manila/exception.py:112
#, python-format
msgid "Bad network configuration: %(reason)s."
msgstr ""

#: manila/exception.py:116
msgid "Not authorized."
msgstr ""

#: manila/exception.py:121
msgid "User does not have admin privileges."
msgstr ""

#: manila/exception.py:125
#, python-format
msgid "Policy doesn't allow %(action)s to be performed."
msgstr ""

#: manila/exception.py:129
msgid "Unacceptable parameters."
msgstr ""

#: manila/exception.py:134
msgid "The request is invalid."
msgstr ""

#: manila/exception.py:138
msgid "The results are invalid."
msgstr ""

#: manila/exception.py:142
#, python-format
msgid "Invalid input received: %(reason)s."
msgstr ""

#: manila/exception.py:146
#, python-format
msgid "Invalid content type %(content_type)s."
msgstr ""

#: manila/exception.py:152 manila/exception.py:455
#, python-format
msgid "%(err)s"
msgstr ""

#: manila/exception.py:156
#, python-format
msgid "Expected a uuid but received %(uuid)s."
msgstr ""

#: manila/exception.py:160
msgid "Resource could not be found."
msgstr ""

#: manila/exception.py:166
msgid "Resource is in use."
msgstr ""

#: manila/exception.py:170
#, python-format
msgid "Network %(share_network_id)s could not be found."
msgstr ""

#: manila/exception.py:174
#, python-format
msgid "Share Server %(share_server_id)s could not be found."
msgstr ""

#: manila/exception.py:178
#, python-format
msgid "Share Server could not be found by filters: %(filters_description)s."
msgstr ""

#: manila/exception.py:183
#, python-format
msgid "Share Server %(share_server_id)s is in use."
msgstr ""

#: manila/exception.py:187
#, python-format
msgid "Share Server %(share_server_id)s failed on creation."
msgstr ""

#: manila/exception.py:191
#, python-format
msgid "Service %(service_id)s could not be found."
msgstr ""

#: manila/exception.py:195
#, python-format
msgid "Host %(host)s could not be found."
msgstr ""

#: manila/exception.py:199
#, python-format
msgid "Scheduler Host Filter %(filter_name)s could not be found."
msgstr ""

#: manila/exception.py:203
#, python-format
msgid "Scheduler Host Weigher %(weigher_name)s could not be found."
msgstr ""

#: manila/exception.py:207
#, python-format
msgid "Could not find binary %(binary)s on host %(host)s."
msgstr ""

#: manila/exception.py:211
#, python-format
msgid "Invalid reservation expiration %(expire)s."
msgstr ""

#: manila/exception.py:215
#, python-format
msgid ""
"Change would make usage less than 0 for the following resources: "
"%(unders)s."
msgstr ""

#: manila/exception.py:220
msgid "Quota could not be found."
msgstr ""

#: manila/exception.py:224
#, python-format
msgid "Quota exists for project %(project_id)s, resource %(resource)s."
msgstr ""

#: manila/exception.py:229
#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr ""

#: manila/exception.py:233
#, python-format
msgid "Quota for user %(user_id)s in project %(project_id)s could not be found."
msgstr ""

#: manila/exception.py:238
#, python-format
msgid "Quota for project %(project_id)s could not be found."
msgstr ""

#: manila/exception.py:242
#, python-format
msgid "Quota class %(class_name)s could not be found."
msgstr ""

#: manila/exception.py:246
#, python-format
msgid "Quota usage for project %(project_id)s could not be found."
msgstr ""

#: manila/exception.py:250
#, python-format
msgid "Quota reservation %(uuid)s could not be found."
msgstr ""

#: manila/exception.py:254
#, python-format
msgid "Quota exceeded for resources: %(overs)s."
msgstr ""

#: manila/exception.py:258
#, python-format
msgid "Migration %(migration_id)s could not be found."
msgstr ""

#: manila/exception.py:262
#, python-format
msgid "Migration not found for instance %(instance_id)s with status %(status)s."
msgstr ""

#: manila/exception.py:267
#, python-format
msgid "File %(file_path)s could not be found."
msgstr ""

#: manila/exception.py:271
#, python-format
msgid "Migration error: %(reason)s."
msgstr ""

#: manila/exception.py:275
#, python-format
msgid "Malformed message body: %(reason)s."
msgstr ""

#: manila/exception.py:279
#, python-format
msgid "Could not find config at %(path)s."
msgstr ""

#: manila/exception.py:283
#, python-format
msgid "Could not load paste app '%(name)s' from %(path)s."
msgstr ""

#: manila/exception.py:287
#, python-format
msgid "No valid host was found. %(reason)s."
msgstr ""

#: manila/exception.py:291
#, python-format
msgid "Host %(host)s is not up or doesn't exist."
msgstr ""

#: manila/exception.py:295
#, python-format
msgid "Quota exceeded: code=%(code)s."
msgstr ""

#: manila/exception.py:302
msgid "Requested share or snapshot exceeds allowed Gigabytes quota."
msgstr ""

#: manila/exception.py:307
#, python-format
msgid "Maximum number of shares allowed (%(allowed)d) exceeded."
msgstr ""

#: manila/exception.py:311
#, python-format
msgid "Maximum number of snapshots allowed (%(allowed)d) exceeded."
msgstr ""

#: manila/exception.py:315
#, python-format
msgid "Maximum number of share-networks allowed (%(allowed)d) exceeded."
msgstr ""

#: manila/exception.py:320
msgid "Unknown Gluster exception."
msgstr ""

#: manila/exception.py:324
#, python-format
msgid "Invalid share: %(reason)s."
msgstr ""

#: manila/exception.py:328
msgid "Maximum number of ports exceeded."
msgstr ""

#: manila/exception.py:332
#, python-format
msgid "Share access %(access_type)s:%(access)s exists."
msgstr ""

#: manila/exception.py:336
#, python-format
msgid "Invalid access_rule: %(reason)s."
msgstr ""

#: manila/exception.py:340
msgid "Deleting $(share_name) share that used."
msgstr ""

#: manila/exception.py:344
#, python-format
msgid "Share backend error: %(msg)s."
msgstr ""

#: manila/exception.py:348 manila/exception.py:399
#, python-format
msgid "Snapshot %(snapshot_id)s could not be found."
msgstr ""

#: manila/exception.py:352
#, python-format
msgid "Deleting snapshot %(snapshot_name)s that has dependent shares."
msgstr ""

#: manila/exception.py:357
#, python-format
msgid "Invalid share snapshot: %(reason)s."
msgstr ""

#: manila/exception.py:361
msgid "Metadata item is not found."
msgstr ""

#: manila/exception.py:365
msgid "Invalid metadata."
msgstr ""

#: manila/exception.py:369
msgid "Invalid metadata size."
msgstr ""

#: manila/exception.py:373
#, python-format
msgid "Security service %(security_service_id)s could not be found."
msgstr ""

#: manila/exception.py:377
#, python-format
msgid ""
"Failed to associate share network %(share_network_id)s and security "
"service %(security_service_id)s: %(reason)s."
msgstr ""

#: manila/exception.py:382
#, python-format
msgid ""
"Failed to dissociate share network %(share_network_id)s and security "
"service %(security_service_id)s: %(reason)s."
msgstr ""

#: manila/exception.py:387
msgid "Invalid volume."
msgstr ""

#: manila/exception.py:391
#, python-format
msgid "Invalid volume type: %(reason)s."
msgstr ""

#: manila/exception.py:395
#, python-format
msgid "Volume %(volume_id)s could not be found."
msgstr ""

#: manila/exception.py:403
#, python-format
msgid "Volume type %(volume_type_id)s could not be found."
msgstr ""

#: manila/exception.py:407
#, python-format
msgid "Volume type with name %(volume_type_name)s could not be found."
msgstr ""

#: manila/exception.py:412
#, python-format
msgid ""
"Volume Type %(volume_type_id)s has no extra specs with key "
"%(extra_specs_key)s."
msgstr ""

#: manila/exception.py:417
#, python-format
msgid ""
"Volume Type %(volume_type_id)s deletion is not allowed with volumes "
"present with the type."
msgstr ""

#: manila/exception.py:422
#, python-format
msgid "Volume Type %(id)s already exists."
msgstr ""

#: manila/exception.py:426
#, python-format
msgid "Cannot create volume_type with name %(name)s and specs %(extra_specs)s."
msgstr ""

#: manila/exception.py:431
#, python-format
msgid "Instance %(instance_id)s could not be found."
msgstr ""

#: manila/exception.py:435
#, python-format
msgid "Bridge %(bridge)s does not exist."
msgstr ""

#: manila/exception.py:439
msgid "Exception in service instance manager occurred."
msgstr ""

#: manila/exception.py:443
msgid "Service Instance is not available."
msgstr ""

#: manila/exception.py:447
msgid "Exception due to NetApp failure."
msgstr ""

#: manila/exception.py:451
#, python-format
msgid "Vserver %(vserver)s is not available."
msgstr ""

#: manila/manager.py:163
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: manila/quota.py:983
#, python-format
msgid "Failed to commit reservations %s"
msgstr ""

#: manila/quota.py:1006
#, python-format
msgid "Failed to roll back reservations %s"
msgstr ""

#: manila/service.py:123
msgid "SIGTERM received"
msgstr ""

#: manila/service.py:173
msgid "Parent process has died unexpectedly, exiting"
msgstr ""

#: manila/service.py:212
msgid "Forking too fast, sleeping"
msgstr ""

#: manila/service.py:230
#, python-format
msgid "Caught %s, exiting"
msgstr ""

#: manila/service.py:235
msgid "Unhandled exception"
msgstr ""

#: manila/service.py:242
#, python-format
msgid "Started child %d"
msgstr ""

#: manila/service.py:252
#, python-format
msgid "Starting %d workers"
msgstr ""

#: manila/service.py:271
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr ""

#: manila/service.py:274
#, python-format
msgid "Child %(pid)d exited with status %(code)d"
msgstr ""

#: manila/service.py:277
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: manila/service.py:285
#, python-format
msgid "_wait_child %d"
msgstr ""

#: manila/service.py:301
#, python-format
msgid "wait wrap.failed %s"
msgstr ""

#: manila/service.py:309
#, python-format
msgid "Caught %s, stopping children"
msgstr ""

#: manila/service.py:320
#, python-format
msgid "Waiting on %d children to exit"
msgstr ""

#: manila/service.py:355
#, python-format
msgid "Starting %(topic)s node (version %(version_string)s)"
msgstr ""

#: manila/service.py:452
msgid "Service killed that has no database entry"
msgstr ""

#: manila/service.py:504
msgid "Recovered model server connection!"
msgstr ""

#: manila/service.py:510
msgid "model server went away"
msgstr ""

#: manila/utils.py:137
msgid "Specify a password or private_key"
msgstr ""

#: manila/utils.py:159
#, python-format
msgid "Error connecting via ssh: %s"
msgstr ""

#: manila/utils.py:360
#, python-format
msgid "Link Local address is not found.:%s"
msgstr ""

#: manila/utils.py:363
#, python-format
msgid "Couldn't get Link Local IP of %(interface)s :%(ex)s"
msgstr ""

#: manila/utils.py:392
#, python-format
msgid "Invalid backend: %s"
msgstr ""

#: manila/utils.py:911
#, python-format
msgid "Unknown byte multiplier: %s"
msgstr ""

#: manila/utils.py:923
#, python-format
msgid "Invalid cidr supplied %s"
msgstr ""

#: manila/wsgi.py:133 manila/openstack/common/sslutils.py:47
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: manila/wsgi.py:136 manila/openstack/common/sslutils.py:50
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: manila/wsgi.py:139 manila/openstack/common/sslutils.py:53
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: manila/wsgi.py:142 manila/openstack/common/sslutils.py:56
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: manila/wsgi.py:175
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr ""

#: manila/wsgi.py:219
#, python-format
msgid "Started %(name)s on %(_host)s:%(_port)s"
msgstr ""

#: manila/wsgi.py:238
msgid "Stopping WSGI server."
msgstr ""

#: manila/wsgi.py:252
msgid "WSGI server has stopped."
msgstr ""

#: manila/wsgi.py:321
msgid "You must implement __call__"
msgstr ""

#: manila/api/auth.py:27
msgid ""
"manila.api.auth:ManilaKeystoneContext is deprecated. Please use "
"manila.api.middleware.auth:ManilaKeystoneContext instead."
msgstr ""

#: manila/api/auth.py:35
msgid ""
"manila.api.auth:pipeline_factory is deprecated. Please use "
"manila.api.middleware.auth:pipeline_factory instead."
msgstr ""

#: manila/api/common.py:76 manila/api/common.py:110
msgid "limit param must be an integer"
msgstr ""

#: manila/api/common.py:79 manila/api/common.py:114
msgid "limit param must be positive"
msgstr ""

#: manila/api/common.py:104
msgid "offset param must be an integer"
msgstr ""

#: manila/api/common.py:118
msgid "offset param must be positive"
msgstr ""

#: manila/api/common.py:146
#, python-format
msgid "marker [%s] not found"
msgstr ""

#: manila/api/extensions.py:183
msgid "Initializing extension manager."
msgstr ""

#: manila/api/extensions.py:199
#, python-format
msgid "Loaded extension: %s"
msgstr ""

#: manila/api/extensions.py:244
#, python-format
msgid "Exception loading extension: %s"
msgstr ""

#: manila/api/extensions.py:279
#, python-format
msgid "osapi_share_extension is set to deprecated path: %s"
msgstr ""

#: manila/api/extensions.py:281
#, python-format
msgid ""
"Please set your flag or manila.conf settings for osapi_share_extension "
"to: %s"
msgstr ""

#: manila/api/extensions.py:290
#, python-format
msgid "Failed to load extension %(ext_factory)s: %(exc)s"
msgstr ""

#: manila/api/extensions.py:359
#, python-format
msgid "Failed to load extension %(classpath)s: %(exc)s"
msgstr ""

#: manila/api/extensions.py:384
#, python-format
msgid "Failed to load extension %(ext_name)s: %(exc)s"
msgstr ""

#: manila/api/sizelimit.py:26
msgid ""
"manila.api.sizelimit:RequestBodySizeLimiter is deprecated. Please use "
"manila.api.middleware.sizelimit:RequestBodySizeLimiter instead"
msgstr ""

#: manila/api/xmlutil.py:269
msgid "element is not a child"
msgstr ""

#: manila/api/xmlutil.py:418
msgid "root element selecting a list"
msgstr ""

#: manila/api/xmlutil.py:743
#, python-format
msgid "Template tree mismatch; adding slave %(slavetag)s to master %(mastertag)s"
msgstr ""

#: manila/api/xmlutil.py:865
msgid "subclasses must implement construct()!"
msgstr ""

#: manila/api/contrib/quotas.py:72
msgid "Quota limit must be -1 or greater."
msgstr ""

#: manila/api/contrib/quotas.py:76
#, python-format
msgid "Quota limit must greater than %s."
msgstr ""

#: manila/api/contrib/quotas.py:79
#, python-format
msgid "Quota limit must less than %s."
msgstr ""

#: manila/api/contrib/quotas.py:152 manila/api/contrib/quotas.py:178
#, python-format
msgid "Quota '%(value)s' for %(key)s should be integer."
msgstr ""

#: manila/api/contrib/quotas.py:160
#, python-format
msgid "Bad key(s) %s in quota_set"
msgstr ""

#: manila/api/contrib/quotas.py:193
#, python-format
msgid ""
"Quota value %(value)s for %(key)s are greater than already used and "
"reserved %(quota_used)s"
msgstr ""

#: manila/api/contrib/share_actions.py:81
msgid "Invalid CN (common name). Must be 1-64 chars long"
msgstr ""

#: manila/api/contrib/share_actions.py:136
msgid "Only 'ip','user',or'cert' access types are supported."
msgstr ""

#: manila/api/contrib/types_extra_specs.py:68
msgid "Invalid request body"
msgstr ""

#: manila/api/contrib/types_extra_specs.py:101
msgid "Request body empty"
msgstr ""

#: manila/api/contrib/types_extra_specs.py:105
#: manila/api/v1/share_metadata.py:76
msgid "Request body and URI mismatch"
msgstr ""

#: manila/api/contrib/types_extra_specs.py:108
#: manila/api/v1/share_metadata.py:80
msgid "Request body contains too many items"
msgstr ""

#: manila/api/contrib/types_extra_specs.py:148
msgid ""
"Key names can only contain alphanumeric characters, underscores, periods,"
" colons and hyphens."
msgstr ""

#: manila/api/middleware/auth.py:106
msgid "Invalid service catalog json."
msgstr ""

#: manila/api/middleware/fault.py:45
#, python-format
msgid "Caught error: %s"
msgstr ""

#: manila/api/middleware/fault.py:54 manila/api/openstack/wsgi.py:885
#, python-format
msgid "%(url)s returned with HTTP %(status)d"
msgstr ""

#: manila/api/middleware/sizelimit.py:55 manila/api/middleware/sizelimit.py:64
#: manila/api/middleware/sizelimit.py:78
msgid "Request is too large."
msgstr ""

#: manila/api/openstack/__init__.py:74
msgid "Must specify an ExtensionManager class"
msgstr ""

#: manila/api/openstack/__init__.py:110
#, python-format
msgid ""
"Extension %(ext_name)s: Cannot extend resource %(collection)s: No such "
"resource"
msgstr ""

#: manila/api/openstack/__init__.py:129
msgid ""
"manila.api.openstack:FaultWrapper is deprecated. Please use "
"manila.api.middleware.fault:FaultWrapper instead."
msgstr ""

#: manila/api/openstack/urlmap.py:26
msgid ""
"manila.api.openstack.urlmap:urlmap_factory is deprecated. Please use "
"manila.api.urlmap:urlmap_factory instead."
msgstr ""

#: manila/api/openstack/wsgi.py:134 manila/api/openstack/wsgi.py:537
msgid "cannot understand JSON"
msgstr ""

#: manila/api/openstack/wsgi.py:158
msgid "cannot understand XML"
msgstr ""

#: manila/api/openstack/wsgi.py:542
msgid "too many body keys"
msgstr ""

#: manila/api/openstack/wsgi.py:581
#, python-format
msgid "Exception handling resource: %s"
msgstr ""

#: manila/api/openstack/wsgi.py:585
#, python-format
msgid "Fault thrown: %s"
msgstr ""

#: manila/api/openstack/wsgi.py:588
#, python-format
msgid "HTTP exception thrown: %s"
msgstr ""

#: manila/api/openstack/wsgi.py:815
#, python-format
msgid "There is no such action: %s"
msgstr ""

#: manila/api/openstack/wsgi.py:818 manila/api/openstack/wsgi.py:831
#: manila/api/v1/share_metadata.py:54 manila/api/v1/share_metadata.py:72
#: manila/api/v1/share_metadata.py:97 manila/api/v1/share_metadata.py:119
msgid "Malformed request body"
msgstr ""

#: manila/api/openstack/wsgi.py:828
msgid "Unsupported Content-Type"
msgstr ""

#: manila/api/openstack/wsgi.py:840
msgid "Malformed request url"
msgstr ""

#: manila/api/openstack/wsgi.py:888
#, python-format
msgid "%(url)s returned a fault: %(e)s"
msgstr ""

#: manila/api/openstack/volume/__init__.py:26
msgid ""
"manila.api.openstack.volume:APIRouter is deprecated. Please use "
"manila.api.v1.router:APIRouter instead."
msgstr ""

#: manila/api/openstack/volume/versions.py:27
msgid ""
"manila.api.openstack.volume.versions.Versions is deprecated. Please use "
"manila.api.versions.Versions instead."
msgstr ""

#: manila/api/v1/limits.py:138
#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr ""

#: manila/api/v1/limits.py:264
msgid "This request was rate-limited."
msgstr ""

#: manila/api/v1/security_service.py:84
#, python-format
msgid "Delete security service with id: %s"
msgstr ""

#: manila/api/v1/security_service.py:209
#, python-format
msgid ""
"Cannot update security service %s. It is attached to share network with "
"share server associated. Only 'name' and 'description' fields are "
"available for update."
msgstr ""

#: manila/api/v1/security_service.py:237
#, python-format
msgid ""
"Invalid type %(type)s specified for security service. Valid types are "
"%(types)s"
msgstr ""

#: manila/api/v1/share_metadata.py:38 manila/api/v1/share_metadata.py:115
#: manila/api/v1/share_metadata.py:154
msgid "share does not exist"
msgstr ""

#: manila/api/v1/share_metadata.py:137 manila/api/v1/share_metadata.py:147
msgid "Metadata item was not found"
msgstr ""

#: manila/api/v1/share_networks.py:110
#, python-format
msgid "Cannot delete share network %s. There are share servers using it"
msgstr ""

#: manila/api/v1/share_networks.py:120
msgid "Failed to update usages deleting share-network."
msgstr ""

#: manila/api/v1/share_networks.py:228
#, python-format
msgid ""
"Cannot update share network %s. It is used by share servers. Only 'name' "
"and 'description' fields are available for update"
msgstr ""

#: manila/api/v1/share_networks.py:267
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create share-network "
"(%(d_consumed)d of %(d_quota)d already consumed)"
msgstr ""

#: manila/api/v1/share_networks.py:295
#, python-format
msgid "Share networks does not have %s action"
msgstr ""

#: manila/api/v1/share_networks.py:304
msgid "Cannot add security services. Share network is used."
msgstr ""

#: manila/api/v1/share_networks.py:310
#, python-format
msgid ""
"Cannot add security service to share network. Security service with "
"'%(ss_type)s' type already added to '%(sn_id)s' share network"
msgstr ""

#: manila/api/v1/share_networks.py:337
msgid "Cannot remove security services. Share network is used."
msgstr ""

#: manila/api/v1/share_servers.py:142
#, python-format
msgid ""
"Share server's actual status is %(status)s, allowed statuses for deletion"
" are %(allowed_statuses)s."
msgstr ""

#: manila/api/v1/share_snapshots.py:85
#, python-format
msgid "Delete snapshot with id: %s"
msgstr ""

#: manila/api/v1/share_snapshots.py:184
#, python-format
msgid "Create snapshot from share %s"
msgstr ""

#: manila/api/v1/shares.py:87
#, python-format
msgid "Delete share with id: %s"
msgstr ""

#: manila/api/v1/shares.py:215
#, python-format
msgid "Create %(share_proto)s share of %(size)s GB"
msgstr ""

#: manila/api/v1/shares.py:272
msgid "Volume type not found."
msgstr ""

#: manila/api/v1/volume_types.py:44
msgid "Volume type not found"
msgstr ""

#: manila/common/config.py:102
msgid "Deploy v1 of the Manila API."
msgstr ""

#: manila/common/config.py:105
msgid "Deploy v2 of the Manila API."
msgstr ""

#: manila/db/migrations/alembic/versions/162a3e673105_manila_init.py:403
msgid "Exception while creating table."
msgstr ""

#: manila/db/sqlalchemy/api.py:83
msgid "Use of empty request context is deprecated"
msgstr ""

#: manila/db/sqlalchemy/api.py:196
#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr ""

#: manila/db/sqlalchemy/api.py:948
#, python-format
msgid "Change will make usage less than 0 for the following resources: %s"
msgstr ""

#: manila/db/sqlalchemy/api.py:1218 manila/db/sqlalchemy/api.py:1462
#, python-format
msgid "Wrong sorting key provided - '%s'."
msgstr ""

#: manila/db/sqlalchemy/api.py:1225 manila/db/sqlalchemy/api.py:1469
#, python-format
msgid ""
"Wrong sorting data provided: sort key is '%(sort_key)s' and sort "
"direction is '%(sort_dir)s'."
msgstr ""

#: manila/db/sqlalchemy/api.py:1452
#, python-format
msgid "Wrong 'usage' key provided - '%(key)s'. Expected keys are '%(ek)s'."
msgstr ""

#: manila/db/sqlalchemy/api.py:2118
#, python-format
msgid "VolumeType %s deletion failed, VolumeType in use."
msgstr ""

#: manila/network/linux/interface.py:35
msgid "Name of Open vSwitch bridge to use."
msgstr ""

#: manila/network/linux/interface.py:157 manila/network/linux/interface.py:202
#, python-format
msgid "Device %s already exists"
msgstr ""

#: manila/network/linux/interface.py:173 manila/network/linux/interface.py:215
#, python-format
msgid "Failed unplugging interface '%s'"
msgstr ""

#: manila/network/linux/ip_lib.py:395
msgid "No namespace defined for parent"
msgstr ""

#: manila/network/linux/ovs_lib.py:48
#, python-format
msgid "Unable to execute %(cmd)s. Exception: %(exception)s"
msgstr ""

#: manila/network/neutron/api.py:132
#, python-format
msgid "Neutron error creating port on network %s"
msgstr ""

#: manila/openstack/common/lockutils.py:101
#, python-format
msgid "Unable to acquire lock on `%(filename)s` due to %(exception)s"
msgstr ""

#: manila/openstack/common/log.py:287
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: manila/openstack/common/log.py:395
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: manila/openstack/common/log.py:456
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: manila/openstack/common/log.py:707
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: manila/openstack/common/policy.py:97
msgid "The JSON file that defines policies."
msgstr ""

#: manila/openstack/common/policy.py:100
msgid "Default rule. Enforced when a requested rule is not found."
msgstr ""

#: manila/openstack/common/policy.py:104
msgid "Directories where policy configuration files are stored"
msgstr ""

#: manila/openstack/common/policy.py:119
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: manila/openstack/common/policy.py:213
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: manila/openstack/common/processutils.py:59
msgid "Unexpected error while running command."
msgstr ""

#: manila/openstack/common/processutils.py:62
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: manila/openstack/common/processutils.py:143
#, python-format
msgid "Got unknown keyword args: %r"
msgstr ""

#: manila/openstack/common/processutils.py:148
msgid "Command requested root, but did not specify a root helper."
msgstr ""

#: manila/openstack/common/processutils.py:158
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: manila/openstack/common/processutils.py:206
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: manila/openstack/common/processutils.py:248
msgid "Environment not supported over SSH"
msgstr ""

#: manila/openstack/common/processutils.py:252
msgid "process_input not supported over SSH"
msgstr ""

#: manila/openstack/common/sslutils.py:95
#, python-format
msgid "Invalid SSL version : %s"
msgstr ""

#: manila/scheduler/chance.py:50 manila/scheduler/simple.py:90
msgid "Is the appropriate service running?"
msgstr ""

#: manila/scheduler/chance.py:55
msgid "Could not find another host"
msgstr ""

#: manila/scheduler/driver.py:86
msgid "Must implement a fallback schedule"
msgstr ""

#: manila/scheduler/driver.py:90
msgid "Must implement schedule_create_share"
msgstr ""

#: manila/scheduler/filter_scheduler.py:76
msgid "Invalid value for 'scheduler_max_attempts', must be >=1"
msgstr ""

#: manila/scheduler/filter_scheduler.py:189
#, python-format
msgid "Exceeded max scheduling attempts %(max_attempts)d for share %(share_id)s"
msgstr ""

#: manila/scheduler/filter_scheduler.py:211
#, python-format
msgid ""
"Error scheduling %(share_id)s from last share-service: %(last_host)s : "
"%(exc)s"
msgstr ""

#: manila/scheduler/host_manager.py:270
msgid "service is down or disabled."
msgstr ""

#: manila/scheduler/manager.py:93
#, python-format
msgid "Failed to schedule_%(method)s: %(ex)s"
msgstr ""

#: manila/scheduler/scheduler_options.py:68
#, python-format
msgid "Could not stat scheduler options file %(filename)s: '%(e)s'"
msgstr ""

#: manila/scheduler/scheduler_options.py:78
#, python-format
msgid "Could not decode scheduler options: '%(e)s'"
msgstr ""

#: manila/scheduler/simple.py:78
msgid "Not enough allocatable share gigabytes remaining"
msgstr ""

#: manila/scheduler/filters/capacity_filter.py:38
msgid "Free capacity not set: volume node info collection broken."
msgstr ""

#: manila/scheduler/filters/capacity_filter.py:52
#, python-format
msgid ""
"Insufficient free space for volume creation (requested / avail): "
"%(requested)s/%(available)s"
msgstr ""

#: manila/share/api.py:70
msgid "status must be available"
msgstr ""

#: manila/share/api.py:89
#, python-format
msgid "Share size '%s' must be an integer and greater than 0"
msgstr ""

#: manila/share/api.py:94
#, python-format
msgid "Share size '%s' must be equal or greater than snapshot size"
msgstr ""

#: manila/share/api.py:101
msgid ""
"Invalid volume_type provided (requested type must match source snapshot, "
"or be omitted). You should omit the argument."
msgstr ""

#: manila/share/api.py:109
#, python-format
msgid "Invalid share type provided: %s"
msgstr ""

#: manila/share/api.py:123
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG share "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: manila/share/api.py:132
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create share (%(d_consumed)d "
"shares already consumed)"
msgstr ""

#: manila/share/api.py:221
msgid "Failed to update quota for deleting share"
msgstr ""

#: manila/share/api.py:229
msgid "Share status must be available or error"
msgstr ""

#: manila/share/api.py:234
#, python-format
msgid "Share still has %d dependent snapshots"
msgstr ""

#: manila/share/api.py:261
msgid "must be available"
msgstr ""

#: manila/share/api.py:277
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG snapshot "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: manila/share/api.py:286
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create snapshot (%(d_consumed)d "
"snapshots already consumed)"
msgstr ""

#: manila/share/api.py:321
msgid "Share Snapshot status must be 'available' or 'error'."
msgstr ""

#: manila/share/api.py:356
#, python-format
msgid "Wrong metadata filter provided: %s."
msgstr ""

#: manila/share/api.py:365
#, python-format
msgid "Wrong extra specs filter provided: %s."
msgstr ""

#: manila/share/api.py:369
#, python-format
msgid "Wrong sort_key filter provided: '%s'."
msgstr ""

#: manila/share/api.py:373
#, python-format
msgid "Wrong sort_dir filter provided: '%s'."
msgstr ""

#: manila/share/api.py:423
#, python-format
msgid "Wrong '%(k)s' filter provided: '%(v)s'."
msgstr ""

#: manila/share/api.py:454 manila/share/api.py:477
msgid "Share host is None"
msgstr ""

#: manila/share/api.py:457 manila/share/api.py:480
msgid "Share status must be available"
msgstr ""

#: manila/share/api.py:491
msgid "Access policy should be active or in error state"
msgstr ""

#: manila/share/api.py:527
msgid "Metadata property key is blank"
msgstr ""

#: manila/share/api.py:531
msgid "Metadata property key is greater than 255 characters"
msgstr ""

#: manila/share/api.py:535
msgid "Metadata property value is greater than 1023 characters"
msgstr ""

#: manila/share/driver.py:76
#, python-format
msgid "Recovering from a failed execute. Try number %s"
msgstr ""

#: manila/share/manager.py:91
#, python-format
msgid ""
"Caught exception trying ensure share '%(s_id)s'. Exception: \n"
"%(e)s."
msgstr ""

#: manila/share/manager.py:108
#, python-format
msgid ""
"Unexpected exception during share access allow operation. Share id is "
"'%(s_id)s', access rule type is '%(ar_type)s', access rule id is "
"'%(ar_id)s', exception is '%(e)s'."
msgstr ""

#: manila/share/manager.py:120
#, python-format
msgid "Share %(name)s: skipping export, because it has '%(status)s' status."
msgstr ""

#: manila/share/manager.py:174
msgid "Share server created successfully."
msgstr ""

#: manila/share/manager.py:176
#, python-format
msgid "Used already existed share server '%(share_server_id)s'"
msgstr ""

#: manila/share/manager.py:216
#, python-format
msgid "Share server %s does not exist."
msgstr ""

#: manila/share/manager.py:226
msgid "Failed to get share server for share creation."
msgstr ""

#: manila/share/manager.py:245
#, python-format
msgid "Share %s failed on creation."
msgstr ""

#: manila/share/manager.py:248
msgid "Share created successfully."
msgstr ""

#: manila/share/manager.py:280
msgid "Failed to update usages deleting share"
msgstr ""

#: manila/share/manager.py:283
#, python-format
msgid "Share %s: deleted successfully."
msgstr ""

#: manila/share/manager.py:354
msgid "Failed to update usages deleting snapshot"
msgstr ""

#: manila/share/manager.py:397
msgid "Updating share status"
msgstr ""

#: manila/share/manager.py:483
#, python-format
msgid "Share server %s failed on deletion."
msgstr ""

#: manila/share/manager.py:492
msgid "Share server deleted successfully."
msgstr ""

#: manila/share/volume_types.py:39
#, python-format
msgid "DB error: %s"
msgstr ""

#: manila/share/volume_types.py:48 manila/share/volume_types.py:94
msgid "id cannot be None"
msgstr ""

#: manila/share/volume_types.py:106
msgid "name cannot be None"
msgstr ""

#: manila/share/volume_types.py:125
#, python-format
msgid ""
"Default volume type is not found, please check default_volume_type "
"config: %s"
msgstr ""

#: manila/share/drivers/generic.py:90
msgid "Share server not found."
msgstr ""

#: manila/share/drivers/generic.py:92
msgid "Share server backend details missing."
msgstr ""

#: manila/share/drivers/generic.py:224
#, python-format
msgid "Failed to sync mount files on server '%s'."
msgstr ""

#: manila/share/drivers/generic.py:231
#, python-format
msgid "Failed to mount all shares on server '%s'."
msgstr ""

#: manila/share/drivers/generic.py:264
#, python-format
msgid "Mount point '%(path)s' already exists on server '%(server)s'."
msgstr ""

#: manila/share/drivers/generic.py:290
#, python-format
msgid "Mount point '%(path)s' does not exist on server '%(server)s'."
msgstr ""

#: manila/share/drivers/generic.py:311
#, python-format
msgid "Volume %s is already attached to another instance"
msgstr ""

#: manila/share/drivers/generic.py:324
#, python-format
msgid "Failed to attach volume %s"
msgstr ""

#: manila/share/drivers/generic.py:328
#, python-format
msgid "Volume have not been attached in %ss. Giving up"
msgstr ""

#: manila/share/drivers/generic.py:343
msgid "Error. Ambiguous volumes"
msgstr ""

#: manila/share/drivers/generic.py:358
msgid "Error. Ambiguous volume snaphots"
msgstr ""

#: manila/share/drivers/generic.py:386
#, python-format
msgid "Volume have not been detached in %ss. Giving up"
msgstr ""

#: manila/share/drivers/generic.py:407
msgid "Failed to create volume"
msgstr ""

#: manila/share/drivers/generic.py:412
#, python-format
msgid "Volume have not been created in %ss. Giving up"
msgstr ""

#: manila/share/drivers/generic.py:434
#, python-format
msgid "Volume have not been deleted in %ss. Giving up"
msgstr ""

#: manila/share/drivers/generic.py:507
msgid "Failed to create volume snapshot"
msgstr ""

#: manila/share/drivers/generic.py:515
#, python-format
msgid "Volume snapshot have not been created in %ss. Giving up"
msgstr ""

#: manila/share/drivers/generic.py:539
#, python-format
msgid "Volume snapshot have not been deleted in %ss. Giving up"
msgstr ""

#: manila/share/drivers/generic.py:674
#, python-format
msgid "NFS server is not installed on %s"
msgstr ""

#: manila/share/drivers/generic.py:765
#, python-format
msgid "Share section %s already defined."
msgstr ""

#: manila/share/drivers/generic.py:789
#, python-format
msgid "Caught error trying delete share: %(error)s, trying delete it forcibly."
msgstr ""

#: manila/share/drivers/generic.py:797
#: manila/share/drivers/emc/plugins/vnx/connection.py:388
#: manila/share/drivers/emc/plugins/vnx/connection.py:443
msgid "Only ip access type allowed."
msgstr ""

#: manila/share/drivers/glusterfs.py:104
msgid ""
"glusterfs_target configuration that specifies the GlusterFS volume to be "
"mounted on the Manila host is not set."
msgstr ""

#: manila/share/drivers/glusterfs.py:114
msgid "mount.glusterfs is not installed"
msgstr ""

#: manila/share/drivers/glusterfs.py:130 manila/share/drivers/glusterfs.py:346
#, python-format
msgid "Error in gluster volume set: %s"
msgstr ""

#: manila/share/drivers/glusterfs.py:151
#, python-format
msgid "%s is already mounted"
msgstr ""

#: manila/share/drivers/glusterfs.py:176
#, python-format
msgid "Error retrieving volume info: %s"
msgstr ""

#: manila/share/drivers/glusterfs.py:245
msgid "GlusterFS control mount is not available"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:95
msgid ""
"glusterfs_targets list seems to be empty! Add one or more gluster volumes"
" to work with in the glusterfs_targets configuration parameter."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:102
#, python-format
msgid "Number of gluster volumes read from config: %(numvols)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:110
msgid "mount.glusterfs is not installed."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:114
msgid "Error running mount.glusterfs."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:123
msgid ""
"No unused gluster volumes available for use as share! Create share won't "
"be supported unless existing shares are deleted or add one or more "
"gluster volumes to work with in the glusterfs_targets configuration "
"parameter."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:129
msgid ""
"Number of gluster volumes in use: %(inuse-numvols)s. Number of gluster "
"volumes available for use as share: %(unused-numvols)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:177
#: manila/share/drivers/glusterfs_native.py:191
#: manila/share/drivers/glusterfs_native.py:205
#, python-format
msgid ""
"Error in gluster volume set during volume setup. Volume: %(volname)s, "
"Option: %(option)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:223
#, python-format
msgid "Error stopping gluster volume. Volume: %(volname)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:234
#, python-format
msgid "Error starting gluster volume. Volume: %(volname)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:245
msgid "Couldn't find a free gluster volume to use."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:257
msgid "Couldn't find the share in used list."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:269
#, python-format
msgid ""
"Unable to mount gluster volume. gluster_export: %(export)s, Error: "
"%(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:281
#, python-format
msgid "Unable to unmount gluster volume. mount_dir: %(mntdir)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:296
#: manila/share/drivers/glusterfs_native.py:310
#: manila/share/drivers/glusterfs_native.py:351
#: manila/share/drivers/glusterfs_native.py:365
#, python-format
msgid ""
"Error in gluster volume set during _wipe_gluster_vol. Volume: "
"%(volname)s, Option: %(option)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:334
#, python-format
msgid ""
"Error trying to wipe gluster volume. gluster_export: %(export)s, Error: "
"%(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:384
#, python-format
msgid "Error creating share %(share_id)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:393
#, python-format
msgid "export_location sent back from create_share: %s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:408
#, python-format
msgid "Invalid request. Ignoring delete_share request for share %(share_id)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:417
#, python-format
msgid "Error during delete_share request for share %(share_id)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:431
msgid "Only 'cert' access type allowed"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:442
#, python-format
msgid ""
"Error in gluster volume set during allow access. Volume: %(volname)s, "
"Option: %(option)s, access_to: %(access_to)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:462
msgid "Only 'cert' access type allowed for access removal."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:474
#, python-format
msgid ""
"Error in gluster volume reset during deny access. Volume: %(volname)s, "
"Option: %(option)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/service_instance.py:135
msgid "Service instance user is not specified"
msgstr ""

#: manila/share/drivers/service_instance.py:152
msgid "Can not receive service tenant id."
msgstr ""

#: manila/share/drivers/service_instance.py:174
msgid "Ambiguous service networks."
msgstr ""

#: manila/share/drivers/service_instance.py:201
#, python-format
msgid ""
"Failed to get service instance ip address. Service network name is "
"'%(net_name)s' and provided data are '%(data)s'."
msgstr ""

#: manila/share/drivers/service_instance.py:223
msgid ""
"Name for service instance security group is not provided. Skipping "
"security group step."
msgstr ""

#: manila/share/drivers/service_instance.py:246
msgid "Ambiguous security_groups."
msgstr ""

#: manila/share/drivers/service_instance.py:258
#, python-format
msgid "Service instance %s does not exist."
msgstr ""

#: manila/share/drivers/service_instance.py:278
#, python-format
msgid "Instance have not been deleted in %ss. Giving up."
msgstr ""

#: manila/share/drivers/service_instance.py:332
msgid "Ambiguous keypairs."
msgstr ""

#: manila/share/drivers/service_instance.py:358
msgid "No appropriate image was found."
msgstr ""

#: manila/share/drivers/service_instance.py:362
msgid "Ambiguous image name."
msgstr ""

#: manila/share/drivers/service_instance.py:374
msgid "Neither service instance password nor key are available."
msgstr ""

#: manila/share/drivers/service_instance.py:381
#, python-format
msgid ""
"No key path is available. May be non-existent key path is provided. Check"
" path_to_private_key (current value %(private_path)s) and "
"path_to_public_key (current value %(public_path)s) in manila "
"configuration file."
msgstr ""

#: manila/share/drivers/service_instance.py:416
msgid "Failed to build service instance."
msgstr ""

#: manila/share/drivers/service_instance.py:426
#, python-format
msgid "Instance have not been spawned in %ss. Giving up."
msgstr ""

#: manila/share/drivers/service_instance.py:460
#, python-format
msgid "SSH connection have not been established in %ss. Giving up."
msgstr ""

#: manila/share/drivers/service_instance.py:537
msgid "Subnet must have gateway."
msgstr ""

#: manila/share/drivers/service_instance.py:548
msgid "Subnet gateway is not attached the router."
msgstr ""

#: manila/share/drivers/service_instance.py:609
msgid "Error. Ambiguous service ports."
msgstr ""

#: manila/share/drivers/service_instance.py:615
#, python-format
msgid "Unable to get host. %s"
msgstr ""

#: manila/share/drivers/service_instance.py:660
msgid "No available cidrs."
msgstr ""

#: manila/share/drivers/service_instance.py:706
msgid "Ambiguous service subnets."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:66
#: manila/share/drivers/emc/plugins/vnx/connection.py:166
#: manila/share/drivers/emc/plugins/vnx/connection.py:355
#, python-format
msgid "Invalid NAS protocol supplied: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:83
msgid "No share server found."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:94
#, python-format
msgid "Could not create file system for %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:111
#, python-format
msgid "Could not create CIFS share. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:118
#, python-format
msgid "Could not disable share access. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:123
#, python-format
msgid "CIFS server %s doesn't have interface, so the share is inaccessible."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:141
#, python-format
msgid "Could not create NFS export for share %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:184
#, python-format
msgid "Could not create check point. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:193
msgid ""
"Driver does not support share deletion without share network specified. "
"Return directly because there is nothing to clean"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:215
#, python-format
msgid "CIFS share %s not found. Skip the deletion"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:225
#, python-format
msgid "Deleting CIFS share %(share_name)s on %(mover)s failed. Reason: %(err)s"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:248
#, python-format
msgid "NFS share %s not found. Skip the deletion"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:254
#, python-format
msgid ""
"Deleting NFS share %(share_name)s on %(mover_name)s failed. Reason: "
"%(err)s"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:281
#, python-format
msgid "Mount point %(path)s on %(vdm)s not found."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:284
#, python-format
msgid "Deleting mount point %(path)s on %(mover_name)s failed. Reason: %(err)s"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:291
msgid "Failed to find the VDM. Try to delete the file system"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:302
#, python-format
msgid "File system %s not found. Skip the deletion"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:308
#, python-format
msgid "Failed to delete file system %(fsid)s. Reason: %(err)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:323
#, python-format
msgid "Check point not found. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:328
#, python-format
msgid "Snapshot: %(name)s not found. Skip the deletion."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:335
#, python-format
msgid "Could not delete check point. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:378
#, python-format
msgid "Could not allow CIFS access. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:396
#, python-format
msgid "Could not allow access to NFS share. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:410
msgid "Unsupported share type"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:432
#, python-format
msgid "Could not deny access to CIFS share. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:452
#, python-format
msgid "Could not deny access to NFS share. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:521
#, python-format
msgid "Could not get Share Server by name %(name)s. Reason: %(err)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:547
#, python-format
msgid "Interface creation failed. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:569
#, python-format
msgid "Could not setup server. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:604
#, python-format
msgid "Could not create VDM %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:613
#, python-format
msgid "Could not get physical device port on mover (id:%s)."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:641
#, python-format
msgid "Failed to create cifs server %(name)s.Reason: %(err)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:656
#, python-format
msgid "Could not create DNS domain. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:692
#, python-format
msgid "Could not find CIFS server by name: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:738
msgid "Could not get storage pool list."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:747
#, python-format
msgid "Could not find the storage pool by name: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:757
#, python-format
msgid "Could not find Data Mover by name: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:769
#, python-format
msgid "Could not find Virtual Data Mover by name: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:779
#, python-format
msgid "Could not find Data Mover by id: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:788
#, python-format
msgid "Could not get CIFS server list for %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:793
#, python-format
msgid "Could not find the CIFS servers on VDM: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:807
#, python-format
msgid "Could not get file system by name: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:838
#, python-format
msgid "Copy content from checkpoint to file system failed. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:858
#, python-format
msgid "Extend the file system failed. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:866
#, python-format
msgid "Could not get mount point. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:910
msgid ""
"Unsupported Security Services. Only support single security service and "
"only support type 'active_directory'"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:918
msgid "Only user access type allowed for cifs share"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:924
msgid "Only single security service with type 'active_directory' supported"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/helper.py:87
#, python-format
msgid ""
"REQ: [%(method)s] %(url)s %(req_hdrs)s\n"
"REQ BODY: %(req_b)s\n"
"RESP: [%(code)s] %(resp_hdrs)s\n"
"RESP BODY: %(resp_b)s\n"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/helper.py:127
#, python-format
msgid "The request is invalid. Reason: %(reason)s"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/helper.py:174
#, python-format
msgid "Translated status from %(old)s to %(new)s. Message: %(info)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/helper.py:1157
#, python-format
msgid "Error running SSH command: %s"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/helper.py:1190
msgid "Found the header of the command /nas/bin/nas_cel -interconnect -l"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:824
#, python-format
msgid "Expected just one %(item)s, got %(more)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:832
#, python-format
msgid "Expected one of %(item)s, got %(child)s under %(parent)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:855
#, python-format
msgid "No parser for node type %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:883
#, python-format
msgid "Expected node type %(expected)s, not %(actual)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:894
#, python-format
msgid "Expected %(attr)s attribute on %(node)s node, but only have %(attrs)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:908
#, python-format
msgid "Invalid extra attributes %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:914
#, python-format
msgid "Unexpected node %(node)s under %(parent)s; wanted %(expected)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:925
#, python-format
msgid "Unexpected non-blank pcdata node %(node)s under %(parent)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:938
#, python-format
msgid "Expected either zero or one of %(node)s under %(parent)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:959
#, python-format
msgid "Expected one of %(expected)s under %(parent)s, got %(actual)s."
msgstr ""

#: manila/share/drivers/netapp/api.py:424
#, python-format
msgid "No element by given name %s."
msgstr ""

#: manila/share/drivers/netapp/api.py:444
msgid "Not a valid value for NaElement."
msgstr ""

#: manila/share/drivers/netapp/api.py:448
msgid "NaElement name cannot be null."
msgstr ""

#: manila/share/drivers/netapp/api.py:493
msgid "Type cannot be converted into NaElement."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:84
msgid "Share server is not provided."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:88
msgid ""
"Vserver name is absent in backend details. Please check whether vserver "
"was created properly or not."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:102
msgid "NetApp configuration missing."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:166
#, python-format
msgid "Could not get licenses list. %s."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:176
#, python-format
msgid "Available licenses on '%(backend)s' are %(licenses)s."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:259
#, python-format
msgid "Data port does not exist for node %s."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:288
#, python-format
msgid "Have not found aggregates match pattern %s"
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:319
#, python-format
msgid "Failed to create vlan %(vlan)s on port %(port)s. %(err_msg)"
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:358
#, python-format
msgid "There is no license for %s at Ontap"
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:366
#, python-format
msgid "Invalid NAS protocol supplied: %s. "
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:410
msgid "Failed to create network interface"
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:442
#, python-format
msgid "Unsupported protocol %s for NetApp driver"
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:491
msgid "DNS exists for vserver."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:494
#, python-format
msgid "Failed to configure DNS. %s"
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:516
#, python-format
msgid "Failed to configure Kerberos. %s"
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:523
msgid "Cannot set up kerberos. There are no lifs configured"
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:554
#, python-format
msgid "Failed to create CIFS server entry. %s."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:597
#, python-format
msgid "No aggregate assigned to vserver %s"
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:712
#, python-format
msgid "Share %s does not exist."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:727
#, python-format
msgid "Cannot find network interfaces for vserver %s."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:822
#, python-format
msgid "Vserver %s does not exist."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:833
#, python-format
msgid "Volume %s is already offline."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:841
#, python-format
msgid "Error deleting vserver. Vserver %s has shares."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:857
#, python-format
msgid "CIFS server does not exist for vserver %s"
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:1159
msgid ""
"Cluster Mode supports only 'user' type for share access rules with CIFS "
"protocol."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:1185
#, python-format
msgid "User %s does not exist."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:1187
#, python-format
msgid "Rule %s does not exist."
msgstr ""

#: manila/volume/cinder.py:227
msgid "status must be 'in-use'"
msgstr ""

#: manila/volume/cinder.py:232
msgid "status must be 'available'"
msgstr ""

#: manila/volume/cinder.py:235
msgid "already attached"
msgstr ""

#: manila/volume/cinder.py:239
msgid "Instance and volume not in same availability_zone"
msgstr ""

#: manila/volume/cinder.py:244
msgid "already detached"
msgstr ""

