# Translations template for manila.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the manila project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: manila 2015.1.dev88.ga2b1757\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-11-14 06:14+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: manila/context.py:97
#, python-format
msgid "read_deleted can only be one of 'no', 'yes' or 'only', not %r"
msgstr ""

#: manila/exception.py:69
msgid "An unknown exception occurred."
msgstr ""

#: manila/exception.py:111
msgid "Exception due to network failure."
msgstr ""

#: manila/exception.py:115
#, python-format
msgid "Bad network configuration: %(reason)s."
msgstr ""

#: manila/exception.py:119
msgid "Not authorized."
msgstr ""

#: manila/exception.py:124
msgid "User does not have admin privileges."
msgstr ""

#: manila/exception.py:128
#, python-format
msgid "Policy doesn't allow %(action)s to be performed."
msgstr ""

#: manila/exception.py:132
msgid "Unacceptable parameters."
msgstr ""

#: manila/exception.py:137
msgid "The request is invalid."
msgstr ""

#: manila/exception.py:141
msgid "The results are invalid."
msgstr ""

#: manila/exception.py:145
#, python-format
msgid "Invalid input received: %(reason)s."
msgstr ""

#: manila/exception.py:149
#, python-format
msgid "Invalid content type %(content_type)s."
msgstr ""

#: manila/exception.py:155 manila/exception.py:458
#, python-format
msgid "%(err)s"
msgstr ""

#: manila/exception.py:159
#, python-format
msgid "Expected a uuid but received %(uuid)s."
msgstr ""

#: manila/exception.py:163
msgid "Resource could not be found."
msgstr ""

#: manila/exception.py:169
msgid "Resource is in use."
msgstr ""

#: manila/exception.py:173
#, python-format
msgid "Network %(share_network_id)s could not be found."
msgstr ""

#: manila/exception.py:177
#, python-format
msgid "Share Server %(share_server_id)s could not be found."
msgstr ""

#: manila/exception.py:181
#, python-format
msgid "Share Server could not be found by filters: %(filters_description)s."
msgstr ""

#: manila/exception.py:186
#, python-format
msgid "Share Server %(share_server_id)s is in use."
msgstr ""

#: manila/exception.py:190
#, python-format
msgid "Share Server %(share_server_id)s failed on creation."
msgstr ""

#: manila/exception.py:194
#, python-format
msgid "Service %(service_id)s could not be found."
msgstr ""

#: manila/exception.py:198
#, python-format
msgid "Host %(host)s could not be found."
msgstr ""

#: manila/exception.py:202
#, python-format
msgid "Scheduler Host Filter %(filter_name)s could not be found."
msgstr ""

#: manila/exception.py:206
#, python-format
msgid "Scheduler Host Weigher %(weigher_name)s could not be found."
msgstr ""

#: manila/exception.py:210
#, python-format
msgid "Could not find binary %(binary)s on host %(host)s."
msgstr ""

#: manila/exception.py:214
#, python-format
msgid "Invalid reservation expiration %(expire)s."
msgstr ""

#: manila/exception.py:218
#, python-format
msgid ""
"Change would make usage less than 0 for the following resources: "
"%(unders)s."
msgstr ""

#: manila/exception.py:223
msgid "Quota could not be found."
msgstr ""

#: manila/exception.py:227
#, python-format
msgid "Quota exists for project %(project_id)s, resource %(resource)s."
msgstr ""

#: manila/exception.py:232
#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr ""

#: manila/exception.py:236
#, python-format
msgid "Quota for user %(user_id)s in project %(project_id)s could not be found."
msgstr ""

#: manila/exception.py:241
#, python-format
msgid "Quota for project %(project_id)s could not be found."
msgstr ""

#: manila/exception.py:245
#, python-format
msgid "Quota class %(class_name)s could not be found."
msgstr ""

#: manila/exception.py:249
#, python-format
msgid "Quota usage for project %(project_id)s could not be found."
msgstr ""

#: manila/exception.py:253
#, python-format
msgid "Quota reservation %(uuid)s could not be found."
msgstr ""

#: manila/exception.py:257
#, python-format
msgid "Quota exceeded for resources: %(overs)s."
msgstr ""

#: manila/exception.py:261
#, python-format
msgid "Migration %(migration_id)s could not be found."
msgstr ""

#: manila/exception.py:265
#, python-format
msgid "Migration not found for instance %(instance_id)s with status %(status)s."
msgstr ""

#: manila/exception.py:270
#, python-format
msgid "File %(file_path)s could not be found."
msgstr ""

#: manila/exception.py:274
#, python-format
msgid "Migration error: %(reason)s."
msgstr ""

#: manila/exception.py:278
#, python-format
msgid "Malformed message body: %(reason)s."
msgstr ""

#: manila/exception.py:282
#, python-format
msgid "Could not find config at %(path)s."
msgstr ""

#: manila/exception.py:286
#, python-format
msgid "Could not load paste app '%(name)s' from %(path)s."
msgstr ""

#: manila/exception.py:290
#, python-format
msgid "No valid host was found. %(reason)s."
msgstr ""

#: manila/exception.py:294
#, python-format
msgid "Host %(host)s is not up or doesn't exist."
msgstr ""

#: manila/exception.py:298
#, python-format
msgid "Quota exceeded: code=%(code)s."
msgstr ""

#: manila/exception.py:305
msgid "Requested share or snapshot exceeds allowed Gigabytes quota."
msgstr ""

#: manila/exception.py:310
#, python-format
msgid "Maximum number of shares allowed (%(allowed)d) exceeded."
msgstr ""

#: manila/exception.py:314
#, python-format
msgid "Maximum number of snapshots allowed (%(allowed)d) exceeded."
msgstr ""

#: manila/exception.py:318
#, python-format
msgid "Maximum number of share-networks allowed (%(allowed)d) exceeded."
msgstr ""

#: manila/exception.py:323
msgid "Unknown Gluster exception."
msgstr ""

#: manila/exception.py:327
#, python-format
msgid "Invalid share: %(reason)s."
msgstr ""

#: manila/exception.py:331
msgid "Maximum number of ports exceeded."
msgstr ""

#: manila/exception.py:335
#, python-format
msgid "Share access %(access_type)s:%(access)s exists."
msgstr ""

#: manila/exception.py:339
#, python-format
msgid "Invalid access_rule: %(reason)s."
msgstr ""

#: manila/exception.py:343
msgid "Deleting $(share_name) share that used."
msgstr ""

#: manila/exception.py:347
#, python-format
msgid "Share backend error: %(msg)s."
msgstr ""

#: manila/exception.py:351 manila/exception.py:402
#, python-format
msgid "Snapshot %(snapshot_id)s could not be found."
msgstr ""

#: manila/exception.py:355
#, python-format
msgid "Deleting snapshot %(snapshot_name)s that has dependent shares."
msgstr ""

#: manila/exception.py:360
#, python-format
msgid "Invalid share snapshot: %(reason)s."
msgstr ""

#: manila/exception.py:364
msgid "Metadata item is not found."
msgstr ""

#: manila/exception.py:368
msgid "Invalid metadata."
msgstr ""

#: manila/exception.py:372
msgid "Invalid metadata size."
msgstr ""

#: manila/exception.py:376
#, python-format
msgid "Security service %(security_service_id)s could not be found."
msgstr ""

#: manila/exception.py:380
#, python-format
msgid ""
"Failed to associate share network %(share_network_id)s and security "
"service %(security_service_id)s: %(reason)s."
msgstr ""

#: manila/exception.py:385
#, python-format
msgid ""
"Failed to dissociate share network %(share_network_id)s and security "
"service %(security_service_id)s: %(reason)s."
msgstr ""

#: manila/exception.py:390
msgid "Invalid volume."
msgstr ""

#: manila/exception.py:394
#, python-format
msgid "Invalid volume type: %(reason)s."
msgstr ""

#: manila/exception.py:398
#, python-format
msgid "Volume %(volume_id)s could not be found."
msgstr ""

#: manila/exception.py:406
#, python-format
msgid "Volume type %(volume_type_id)s could not be found."
msgstr ""

#: manila/exception.py:410
#, python-format
msgid "Volume type with name %(volume_type_name)s could not be found."
msgstr ""

#: manila/exception.py:415
#, python-format
msgid ""
"Volume Type %(volume_type_id)s has no extra specs with key "
"%(extra_specs_key)s."
msgstr ""

#: manila/exception.py:420
#, python-format
msgid ""
"Volume Type %(volume_type_id)s deletion is not allowed with volumes "
"present with the type."
msgstr ""

#: manila/exception.py:425
#, python-format
msgid "Volume Type %(id)s already exists."
msgstr ""

#: manila/exception.py:429
#, python-format
msgid "Cannot create volume_type with name %(name)s and specs %(extra_specs)s."
msgstr ""

#: manila/exception.py:434
#, python-format
msgid "Instance %(instance_id)s could not be found."
msgstr ""

#: manila/exception.py:438
#, python-format
msgid "Bridge %(bridge)s does not exist."
msgstr ""

#: manila/exception.py:442
msgid "Exception in service instance manager occurred."
msgstr ""

#: manila/exception.py:446
msgid "Service Instance is not available."
msgstr ""

#: manila/exception.py:450
msgid "Exception due to NetApp failure."
msgstr ""

#: manila/exception.py:454
#, python-format
msgid "Vserver %(vserver)s is not available."
msgstr ""

#: manila/utils.py:137
msgid "Specify a password or private_key"
msgstr ""

#: manila/utils.py:159
#, python-format
msgid "Error connecting via ssh: %s"
msgstr ""

#: manila/utils.py:360
#, python-format
msgid "Link Local address is not found.:%s"
msgstr ""

#: manila/utils.py:363
#, python-format
msgid "Couldn't get Link Local IP of %(interface)s :%(ex)s"
msgstr ""

#: manila/utils.py:392
#, python-format
msgid "Invalid backend: %s"
msgstr ""

#: manila/utils.py:911
#, python-format
msgid "Unknown byte multiplier: %s"
msgstr ""

#: manila/utils.py:923
#, python-format
msgid "Invalid cidr supplied %s"
msgstr ""

#: manila/wsgi.py:134 manila/openstack/common/sslutils.py:47
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: manila/wsgi.py:137 manila/openstack/common/sslutils.py:50
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: manila/wsgi.py:140 manila/openstack/common/sslutils.py:53
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: manila/wsgi.py:143 manila/openstack/common/sslutils.py:56
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: manila/wsgi.py:176
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr ""

#: manila/wsgi.py:322
msgid "You must implement __call__"
msgstr ""

#: manila/api/common.py:76 manila/api/common.py:110
msgid "limit param must be an integer"
msgstr ""

#: manila/api/common.py:79 manila/api/common.py:114
msgid "limit param must be positive"
msgstr ""

#: manila/api/common.py:104
msgid "offset param must be an integer"
msgstr ""

#: manila/api/common.py:118
msgid "offset param must be positive"
msgstr ""

#: manila/api/common.py:146
#, python-format
msgid "marker [%s] not found"
msgstr ""

#: manila/api/xmlutil.py:269
msgid "element is not a child"
msgstr ""

#: manila/api/xmlutil.py:418
msgid "root element selecting a list"
msgstr ""

#: manila/api/xmlutil.py:743
#, python-format
msgid "Template tree mismatch; adding slave %(slavetag)s to master %(mastertag)s"
msgstr ""

#: manila/api/xmlutil.py:865
msgid "subclasses must implement construct()!"
msgstr ""

#: manila/api/contrib/quotas.py:72
msgid "Quota limit must be -1 or greater."
msgstr ""

#: manila/api/contrib/quotas.py:76
#, python-format
msgid "Quota limit must greater than %s."
msgstr ""

#: manila/api/contrib/quotas.py:79
#, python-format
msgid "Quota limit must less than %s."
msgstr ""

#: manila/api/contrib/quotas.py:152 manila/api/contrib/quotas.py:178
#, python-format
msgid "Quota '%(value)s' for %(key)s should be integer."
msgstr ""

#: manila/api/contrib/quotas.py:160
#, python-format
msgid "Bad key(s) %s in quota_set"
msgstr ""

#: manila/api/contrib/quotas.py:193
#, python-format
msgid ""
"Quota value %(value)s for %(key)s are greater than already used and "
"reserved %(quota_used)s"
msgstr ""

#: manila/api/contrib/share_actions.py:81
msgid "Invalid CN (common name). Must be 1-64 chars long"
msgstr ""

#: manila/api/contrib/share_actions.py:136
msgid "Only 'ip','user',or'cert' access types are supported."
msgstr ""

#: manila/api/contrib/types_extra_specs.py:68
msgid "Invalid request body"
msgstr ""

#: manila/api/contrib/types_extra_specs.py:101
msgid "Request body empty"
msgstr ""

#: manila/api/contrib/types_extra_specs.py:105
#: manila/api/v1/share_metadata.py:76
msgid "Request body and URI mismatch"
msgstr ""

#: manila/api/contrib/types_extra_specs.py:108
#: manila/api/v1/share_metadata.py:80
msgid "Request body contains too many items"
msgstr ""

#: manila/api/contrib/types_extra_specs.py:148
msgid ""
"Key names can only contain alphanumeric characters, underscores, periods,"
" colons and hyphens."
msgstr ""

#: manila/api/middleware/auth.py:106
msgid "Invalid service catalog json."
msgstr ""

#: manila/api/middleware/sizelimit.py:55 manila/api/middleware/sizelimit.py:64
#: manila/api/middleware/sizelimit.py:78
msgid "Request is too large."
msgstr ""

#: manila/api/openstack/__init__.py:75
msgid "Must specify an ExtensionManager class"
msgstr ""

#: manila/api/openstack/wsgi.py:136 manila/api/openstack/wsgi.py:539
msgid "cannot understand JSON"
msgstr ""

#: manila/api/openstack/wsgi.py:160
msgid "cannot understand XML"
msgstr ""

#: manila/api/openstack/wsgi.py:544
msgid "too many body keys"
msgstr ""

#: manila/api/openstack/wsgi.py:817
#, python-format
msgid "There is no such action: %s"
msgstr ""

#: manila/api/openstack/wsgi.py:820 manila/api/openstack/wsgi.py:833
#: manila/api/v1/share_metadata.py:54 manila/api/v1/share_metadata.py:72
#: manila/api/v1/share_metadata.py:97 manila/api/v1/share_metadata.py:119
msgid "Malformed request body"
msgstr ""

#: manila/api/openstack/wsgi.py:830
msgid "Unsupported Content-Type"
msgstr ""

#: manila/api/openstack/wsgi.py:842
msgid "Malformed request url"
msgstr ""

#: manila/api/openstack/wsgi.py:887
#, python-format
msgid "%(url)s returned with HTTP %(status)d"
msgstr ""

#: manila/api/openstack/wsgi.py:890
#, python-format
msgid "%(url)s returned a fault: %(e)s"
msgstr ""

#: manila/api/openstack/volume/versions.py:27
msgid ""
"manila.api.openstack.volume.versions.Versions is deprecated. Please use "
"manila.api.versions.Versions instead."
msgstr ""

#: manila/api/v1/limits.py:138
#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr ""

#: manila/api/v1/limits.py:264
msgid "This request was rate-limited."
msgstr ""

#: manila/api/v1/security_service.py:210
#, python-format
msgid ""
"Cannot update security service %s. It is attached to share network with "
"share server associated. Only 'name' and 'description' fields are "
"available for update."
msgstr ""

#: manila/api/v1/security_service.py:238
#, python-format
msgid ""
"Invalid type %(type)s specified for security service. Valid types are "
"%(types)s"
msgstr ""

#: manila/api/v1/share_metadata.py:38 manila/api/v1/share_metadata.py:115
#: manila/api/v1/share_metadata.py:154
msgid "share does not exist"
msgstr ""

#: manila/api/v1/share_metadata.py:137 manila/api/v1/share_metadata.py:147
msgid "Metadata item was not found"
msgstr ""

#: manila/api/v1/share_networks.py:112
#, python-format
msgid "Cannot delete share network %s. There are share servers using it"
msgstr ""

#: manila/api/v1/share_networks.py:230
#, python-format
msgid ""
"Cannot update share network %s. It is used by share servers. Only 'name' "
"and 'description' fields are available for update"
msgstr ""

#: manila/api/v1/share_networks.py:297
#, python-format
msgid "Share networks does not have %s action"
msgstr ""

#: manila/api/v1/share_networks.py:306
msgid "Cannot add security services. Share network is used."
msgstr ""

#: manila/api/v1/share_networks.py:312
#, python-format
msgid ""
"Cannot add security service to share network. Security service with "
"'%(ss_type)s' type already added to '%(sn_id)s' share network"
msgstr ""

#: manila/api/v1/share_networks.py:339
msgid "Cannot remove security services. Share network is used."
msgstr ""

#: manila/api/v1/share_servers.py:142
#, python-format
msgid ""
"Share server's actual status is %(status)s, allowed statuses for deletion"
" are %(allowed_statuses)s."
msgstr ""

#: manila/api/v1/shares.py:273
msgid "Volume type not found."
msgstr ""

#: manila/api/v1/volume_types.py:44
msgid "Volume type not found"
msgstr ""

#: manila/common/config.py:102
msgid "Deploy v1 of the Manila API."
msgstr ""

#: manila/common/config.py:105
msgid "Deploy v2 of the Manila API."
msgstr ""

#: manila/db/sqlalchemy/api.py:85
msgid "Use of empty request context is deprecated"
msgstr ""

#: manila/db/sqlalchemy/api.py:198
#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr ""

#: manila/db/sqlalchemy/api.py:1220 manila/db/sqlalchemy/api.py:1464
#, python-format
msgid "Wrong sorting key provided - '%s'."
msgstr ""

#: manila/db/sqlalchemy/api.py:1227 manila/db/sqlalchemy/api.py:1471
#, python-format
msgid ""
"Wrong sorting data provided: sort key is '%(sort_key)s' and sort "
"direction is '%(sort_dir)s'."
msgstr ""

#: manila/db/sqlalchemy/api.py:1454
#, python-format
msgid "Wrong 'usage' key provided - '%(key)s'. Expected keys are '%(ek)s'."
msgstr ""

#: manila/network/linux/interface.py:37
msgid "Name of Open vSwitch bridge to use."
msgstr ""

#: manila/network/linux/ip_lib.py:395
msgid "No namespace defined for parent"
msgstr ""

#: manila/openstack/common/lockutils.py:101
#, python-format
msgid "Unable to acquire lock on `%(filename)s` due to %(exception)s"
msgstr ""

#: manila/openstack/common/log.py:287
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: manila/openstack/common/log.py:395
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: manila/openstack/common/log.py:456
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: manila/openstack/common/log.py:707
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: manila/openstack/common/policy.py:97
msgid "The JSON file that defines policies."
msgstr ""

#: manila/openstack/common/policy.py:100
msgid "Default rule. Enforced when a requested rule is not found."
msgstr ""

#: manila/openstack/common/policy.py:104
msgid "Directories where policy configuration files are stored"
msgstr ""

#: manila/openstack/common/policy.py:119
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: manila/openstack/common/policy.py:213
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: manila/openstack/common/processutils.py:59
msgid "Unexpected error while running command."
msgstr ""

#: manila/openstack/common/processutils.py:62
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: manila/openstack/common/processutils.py:143
#, python-format
msgid "Got unknown keyword args: %r"
msgstr ""

#: manila/openstack/common/processutils.py:148
msgid "Command requested root, but did not specify a root helper."
msgstr ""

#: manila/openstack/common/processutils.py:158
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: manila/openstack/common/processutils.py:206
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: manila/openstack/common/processutils.py:248
msgid "Environment not supported over SSH"
msgstr ""

#: manila/openstack/common/processutils.py:252
msgid "process_input not supported over SSH"
msgstr ""

#: manila/openstack/common/sslutils.py:95
#, python-format
msgid "Invalid SSL version : %s"
msgstr ""

#: manila/scheduler/chance.py:50 manila/scheduler/simple.py:90
msgid "Is the appropriate service running?"
msgstr ""

#: manila/scheduler/chance.py:55
msgid "Could not find another host"
msgstr ""

#: manila/scheduler/driver.py:86
msgid "Must implement a fallback schedule"
msgstr ""

#: manila/scheduler/driver.py:90
msgid "Must implement schedule_create_share"
msgstr ""

#: manila/scheduler/filter_scheduler.py:77
msgid "Invalid value for 'scheduler_max_attempts', must be >=1"
msgstr ""

#: manila/scheduler/filter_scheduler.py:190
#, python-format
msgid "Exceeded max scheduling attempts %(max_attempts)d for share %(share_id)s"
msgstr ""

#: manila/scheduler/simple.py:78
msgid "Not enough allocatable share gigabytes remaining"
msgstr ""

#: manila/share/api.py:72
msgid "status must be available"
msgstr ""

#: manila/share/api.py:91
#, python-format
msgid "Share size '%s' must be an integer and greater than 0"
msgstr ""

#: manila/share/api.py:96
#, python-format
msgid "Share size '%s' must be equal or greater than snapshot size"
msgstr ""

#: manila/share/api.py:103
msgid ""
"Invalid volume_type provided (requested type must match source snapshot, "
"or be omitted). You should omit the argument."
msgstr ""

#: manila/share/api.py:111
#, python-format
msgid "Invalid share type provided: %s"
msgstr ""

#: manila/share/api.py:231
msgid "Share status must be available or error"
msgstr ""

#: manila/share/api.py:236
#, python-format
msgid "Share still has %d dependent snapshots"
msgstr ""

#: manila/share/api.py:263
msgid "must be available"
msgstr ""

#: manila/share/api.py:323
msgid "Share Snapshot status must be 'available' or 'error'."
msgstr ""

#: manila/share/api.py:358
#, python-format
msgid "Wrong metadata filter provided: %s."
msgstr ""

#: manila/share/api.py:367
#, python-format
msgid "Wrong extra specs filter provided: %s."
msgstr ""

#: manila/share/api.py:371
#, python-format
msgid "Wrong sort_key filter provided: '%s'."
msgstr ""

#: manila/share/api.py:375
#, python-format
msgid "Wrong sort_dir filter provided: '%s'."
msgstr ""

#: manila/share/api.py:425
#, python-format
msgid "Wrong '%(k)s' filter provided: '%(v)s'."
msgstr ""

#: manila/share/api.py:456 manila/share/api.py:479
msgid "Share host is None"
msgstr ""

#: manila/share/api.py:459 manila/share/api.py:482
msgid "Share status must be available"
msgstr ""

#: manila/share/api.py:493
msgid "Access policy should be active or in error state"
msgstr ""

#: manila/share/api.py:529
msgid "Metadata property key is blank"
msgstr ""

#: manila/share/api.py:533
msgid "Metadata property key is greater than 255 characters"
msgstr ""

#: manila/share/api.py:537
msgid "Metadata property value is greater than 1023 characters"
msgstr ""

#: manila/share/volume_types.py:49 manila/share/volume_types.py:95
msgid "id cannot be None"
msgstr ""

#: manila/share/volume_types.py:107
msgid "name cannot be None"
msgstr ""

#: manila/share/drivers/generic.py:92
msgid "Share server not found."
msgstr ""

#: manila/share/drivers/generic.py:94
msgid "Share server backend details missing."
msgstr ""

#: manila/share/drivers/generic.py:313
#, python-format
msgid "Volume %s is already attached to another instance"
msgstr ""

#: manila/share/drivers/generic.py:326
#, python-format
msgid "Failed to attach volume %s"
msgstr ""

#: manila/share/drivers/generic.py:330
#, python-format
msgid "Volume have not been attached in %ss. Giving up"
msgstr ""

#: manila/share/drivers/generic.py:345
msgid "Error. Ambiguous volumes"
msgstr ""

#: manila/share/drivers/generic.py:360
msgid "Error. Ambiguous volume snaphots"
msgstr ""

#: manila/share/drivers/generic.py:388
#, python-format
msgid "Volume have not been detached in %ss. Giving up"
msgstr ""

#: manila/share/drivers/generic.py:409
msgid "Failed to create volume"
msgstr ""

#: manila/share/drivers/generic.py:414
#, python-format
msgid "Volume have not been created in %ss. Giving up"
msgstr ""

#: manila/share/drivers/generic.py:436
#, python-format
msgid "Volume have not been deleted in %ss. Giving up"
msgstr ""

#: manila/share/drivers/generic.py:509
msgid "Failed to create volume snapshot"
msgstr ""

#: manila/share/drivers/generic.py:517
#, python-format
msgid "Volume snapshot have not been created in %ss. Giving up"
msgstr ""

#: manila/share/drivers/generic.py:541
#, python-format
msgid "Volume snapshot have not been deleted in %ss. Giving up"
msgstr ""

#: manila/share/drivers/generic.py:676
#, python-format
msgid "NFS server is not installed on %s"
msgstr ""

#: manila/share/drivers/generic.py:767
#, python-format
msgid "Share section %s already defined."
msgstr ""

#: manila/share/drivers/generic.py:799
#: manila/share/drivers/emc/plugins/vnx/connection.py:387
#: manila/share/drivers/emc/plugins/vnx/connection.py:442
msgid "Only ip access type allowed."
msgstr ""

#: manila/share/drivers/glusterfs.py:106
msgid ""
"glusterfs_target configuration that specifies the GlusterFS volume to be "
"mounted on the Manila host is not set."
msgstr ""

#: manila/share/drivers/glusterfs.py:116
msgid "mount.glusterfs is not installed"
msgstr ""

#: manila/share/drivers/glusterfs.py:247
msgid "GlusterFS control mount is not available"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:96
msgid ""
"glusterfs_targets list seems to be empty! Add one or more gluster volumes"
" to work with in the glusterfs_targets configuration parameter."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:111
msgid "mount.glusterfs is not installed."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:115
msgid "Error running mount.glusterfs."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:124
msgid ""
"No unused gluster volumes available for use as share! Create share won't "
"be supported unless existing shares are deleted or add one or more "
"gluster volumes to work with in the glusterfs_targets configuration "
"parameter."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:178
#: manila/share/drivers/glusterfs_native.py:192
#: manila/share/drivers/glusterfs_native.py:206
#, python-format
msgid ""
"Error in gluster volume set during volume setup. Volume: %(volname)s, "
"Option: %(option)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:224
#, python-format
msgid "Error stopping gluster volume. Volume: %(volname)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:235
#, python-format
msgid "Error starting gluster volume. Volume: %(volname)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:246
msgid "Couldn't find a free gluster volume to use."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:258
msgid "Couldn't find the share in used list."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:270
#, python-format
msgid ""
"Unable to mount gluster volume. gluster_export: %(export)s, Error: "
"%(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:282
#, python-format
msgid "Unable to unmount gluster volume. mount_dir: %(mntdir)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:297
#: manila/share/drivers/glusterfs_native.py:311
#: manila/share/drivers/glusterfs_native.py:352
#: manila/share/drivers/glusterfs_native.py:366
#, python-format
msgid ""
"Error in gluster volume set during _wipe_gluster_vol. Volume: "
"%(volname)s, Option: %(option)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:335
#, python-format
msgid ""
"Error trying to wipe gluster volume. gluster_export: %(export)s, Error: "
"%(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:385
#, python-format
msgid "Error creating share %(share_id)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:409
#, python-format
msgid "Invalid request. Ignoring delete_share request for share %(share_id)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:418
#, python-format
msgid "Error during delete_share request for share %(share_id)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:432
msgid "Only 'cert' access type allowed"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:443
#, python-format
msgid ""
"Error in gluster volume set during allow access. Volume: %(volname)s, "
"Option: %(option)s, access_to: %(access_to)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:463
msgid "Only 'cert' access type allowed for access removal."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:475
#, python-format
msgid ""
"Error in gluster volume reset during deny access. Volume: %(volname)s, "
"Option: %(option)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/service_instance.py:136
msgid "Service instance user is not specified"
msgstr ""

#: manila/share/drivers/service_instance.py:153
msgid "Can not receive service tenant id."
msgstr ""

#: manila/share/drivers/service_instance.py:175
msgid "Ambiguous service networks."
msgstr ""

#: manila/share/drivers/service_instance.py:202
#, python-format
msgid ""
"Failed to get service instance ip address. Service network name is "
"'%(net_name)s' and provided data are '%(data)s'."
msgstr ""

#: manila/share/drivers/service_instance.py:247
msgid "Ambiguous security_groups."
msgstr ""

#: manila/share/drivers/service_instance.py:279
#, python-format
msgid "Instance have not been deleted in %ss. Giving up."
msgstr ""

#: manila/share/drivers/service_instance.py:333
msgid "Ambiguous keypairs."
msgstr ""

#: manila/share/drivers/service_instance.py:359
msgid "No appropriate image was found."
msgstr ""

#: manila/share/drivers/service_instance.py:363
msgid "Ambiguous image name."
msgstr ""

#: manila/share/drivers/service_instance.py:375
msgid "Neither service instance password nor key are available."
msgstr ""

#: manila/share/drivers/service_instance.py:418
msgid "Failed to build service instance."
msgstr ""

#: manila/share/drivers/service_instance.py:428
#, python-format
msgid "Instance have not been spawned in %ss. Giving up."
msgstr ""

#: manila/share/drivers/service_instance.py:462
#, python-format
msgid "SSH connection have not been established in %ss. Giving up."
msgstr ""

#: manila/share/drivers/service_instance.py:539
msgid "Subnet must have gateway."
msgstr ""

#: manila/share/drivers/service_instance.py:550
msgid "Subnet gateway is not attached the router."
msgstr ""

#: manila/share/drivers/service_instance.py:611
msgid "Error. Ambiguous service ports."
msgstr ""

#: manila/share/drivers/service_instance.py:617
#, python-format
msgid "Unable to get host. %s"
msgstr ""

#: manila/share/drivers/service_instance.py:662
msgid "No available cidrs."
msgstr ""

#: manila/share/drivers/service_instance.py:708
msgid "Ambiguous service subnets."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:68
#: manila/share/drivers/emc/plugins/vnx/connection.py:168
#: manila/share/drivers/emc/plugins/vnx/connection.py:354
#, python-format
msgid "Invalid NAS protocol supplied: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:85
msgid "No share server found."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:96
#, python-format
msgid "Could not create file system for %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:113
#, python-format
msgid "Could not create CIFS share. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:120
#, python-format
msgid "Could not disable share access. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:125
#, python-format
msgid "CIFS server %s doesn't have interface, so the share is inaccessible."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:143
#, python-format
msgid "Could not create NFS export for share %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:186
#, python-format
msgid "Could not create check point. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:227
#, python-format
msgid "Deleting CIFS share %(share_name)s on %(mover)s failed. Reason: %(err)s"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:256
#, python-format
msgid ""
"Deleting NFS share %(share_name)s on %(mover_name)s failed. Reason: "
"%(err)s"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:309
#, python-format
msgid "Failed to delete file system %(fsid)s. Reason: %(err)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:334
#, python-format
msgid "Could not delete check point. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:377
#, python-format
msgid "Could not allow CIFS access. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:395
#, python-format
msgid "Could not allow access to NFS share. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:409
msgid "Unsupported share type"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:431
#, python-format
msgid "Could not deny access to CIFS share. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:451
#, python-format
msgid "Could not deny access to NFS share. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:520
#, python-format
msgid "Could not get Share Server by name %(name)s. Reason: %(err)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:546
#, python-format
msgid "Interface creation failed. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:602
#, python-format
msgid "Could not create VDM %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:611
#, python-format
msgid "Could not get physical device port on mover (id:%s)."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:639
#, python-format
msgid "Failed to create cifs server %(name)s.Reason: %(err)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:654
#, python-format
msgid "Could not create DNS domain. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:743
#, python-format
msgid "Could not find the storage pool by name: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:753
#, python-format
msgid "Could not find Data Mover by name: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:765
#, python-format
msgid "Could not find Virtual Data Mover by name: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:775
#, python-format
msgid "Could not find Data Mover by id: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:784
#, python-format
msgid "Could not get CIFS server list for %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:789
#, python-format
msgid "Could not find the CIFS servers on VDM: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:803
#, python-format
msgid "Could not get file system by name: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:834
#, python-format
msgid "Copy content from checkpoint to file system failed. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:854
#, python-format
msgid "Extend the file system failed. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:904
msgid ""
"Unsupported Security Services. Only support single security service and "
"only support type 'active_directory'"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:912
msgid "Only user access type allowed for cifs share"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:918
msgid "Only single security service with type 'active_directory' supported"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/helper.py:130
#, python-format
msgid "The request is invalid. Reason: %(reason)s"
msgstr ""

#: manila/share/drivers/netapp/api.py:424
#, python-format
msgid "No element by given name %s."
msgstr ""

#: manila/share/drivers/netapp/api.py:444
msgid "Not a valid value for NaElement."
msgstr ""

#: manila/share/drivers/netapp/api.py:448
msgid "NaElement name cannot be null."
msgstr ""

#: manila/share/drivers/netapp/api.py:493
msgid "Type cannot be converted into NaElement."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:86
msgid "Share server is not provided."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:90
msgid ""
"Vserver name is absent in backend details. Please check whether vserver "
"was created properly or not."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:104
msgid "NetApp configuration missing."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:261
#, python-format
msgid "Data port does not exist for node %s."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:290
#, python-format
msgid "Have not found aggregates match pattern %s"
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:321
#, python-format
msgid "Failed to create vlan %(vlan)s on port %(port)s. %(err_msg)"
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:360
#, python-format
msgid "There is no license for %s at Ontap"
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:368
#, python-format
msgid "Invalid NAS protocol supplied: %s. "
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:444
#, python-format
msgid "Unsupported protocol %s for NetApp driver"
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:496
#, python-format
msgid "Failed to configure DNS. %s"
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:518
#, python-format
msgid "Failed to configure Kerberos. %s"
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:525
msgid "Cannot set up kerberos. There are no lifs configured"
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:556
#, python-format
msgid "Failed to create CIFS server entry. %s."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:599
#, python-format
msgid "No aggregate assigned to vserver %s"
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:729
#, python-format
msgid "Cannot find network interfaces for vserver %s."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:843
#, python-format
msgid "Error deleting vserver. Vserver %s has shares."
msgstr ""

#: manila/share/drivers/netapp/cluster_mode.py:1161
msgid ""
"Cluster Mode supports only 'user' type for share access rules with CIFS "
"protocol."
msgstr ""

#: manila/volume/cinder.py:227
msgid "status must be 'in-use'"
msgstr ""

#: manila/volume/cinder.py:232
msgid "status must be 'available'"
msgstr ""

#: manila/volume/cinder.py:235
msgid "already attached"
msgstr ""

#: manila/volume/cinder.py:239
msgid "Instance and volume not in same availability_zone"
msgstr ""

#: manila/volume/cinder.py:244
msgid "already detached"
msgstr ""

